FROM weastur/poetry:1.6.1-python-3.12-alpine3.17

RUN apk add --no-cache \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    python3-dev \
    && rm -rf /var/cache/apk/*

WORKDIR /workspace

COPY poetry.lock pyproject.toml server.py /workspace/
COPY internal /workspace/internal

RUN poetry install

ENTRYPOINT ["poetry", "run", "python", "server.py"]
